config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :notes
  end


  #resources :notes
  root to: 'home#index'
  get 'users/index'

  get 'home/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  belongs_to :category

  PRIORITIES = [1, 2, 3]

  scope :priority, -> { where.not(priority: nil).order(:priority) }

  def self.priorities_for_select
    [
      ["#1", 1],
      ["#2", 2],
      ["#3", 3]
    ]
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
    @category = Category.find_by_id(params[:category_id])
    @categories = Category.all
  end

  # GET /notes/1/edit
  def edit

    @categories = Category.all
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to category_path(@note.category), notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to category_path(@note.category), notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to category_path(@note.category), notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
      @category = Category.find(params[:category_id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :body, :important, :user_id, :category_id, :priority)
        .merge(user_id: current_user.id)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_with(model: note, url: [@category, @note], local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger" role="alert">
        <p><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</p>
        <ul>
          <% note.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :category %>
    <%= form.select :category_id,
        options_for_select(@categories.collect { |c| [c.title, c.id] }, selected: params["category_id"]),
        {},
        { class: 'form-select' }
     %>
  </div>

  <div class="form-group">
    <%= form.label :important %>
    <%= form.check_box :important, class: "form-check-input" %>
  </div>

  <div class="form-group">
    <%= form.label :priority %>
    <%= form.select :priority,
        Note::priorities_for_select,
        { include_blank: 'Select priority...' },
        { class: 'form-select' }
     %>
  </div>

  <div class="actions">
    <%= form.submit "save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/notes/_note_card.html.erb
<div class="card">
  <h5 class="card-header"><%= note.category.title %></h5>
  <div class="card-body">
    <h5 class="card-title"><%= note.title %></h5>
    <p class="card-text"><%= note.body %></p>
    <a><%= link_to 'Edit', edit_category_note_path(note.category, note), class: 'btn btn-primary' %></a>
    <a><%= link_to 'Destroy', category_note_path(note.category, note), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></a>
  </div>
</div>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Important</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.body %></td>
        <td><%= note.important %></td>
        <td><%= note.user %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>new note</h1>

<%= render 'form', note: @note %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @note.body %>
</p>

<p>
  <strong>Important:</strong>
  <%= @note.important %>
</p>

<p>
  <strong>User:</strong>
  <%= @note.user %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>