config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :notes
  end


  #resources :notes
  root to: 'home#index'
  get 'users/index'

  get 'home/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Self#Notes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-dark border-bottom shadow-sm">
      <p class="h5 my-0 me-md-auto fw-normal text-white">Self#Notes</p>
      <nav class="my-2 my-md-0 me-md-3">
        <% if user_signed_in? %>
          <a class="p-2 text-white" href="/">Notes</a>
          <a class=" dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.name %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item') %>
          </ul>
        <% else %>
          <a><%= link_to 'Log in', new_user_session_path, class: 'btn btn-outline-primary' %></a>
          <a><%= link_to 'Register', new_user_registration_path, class: 'btn btn-outline-primary' %></a>
        <% end %>
      </nav>
    </header>

    <div class="d-flex" id="wrapper">
      <% if @categories %>
        <div class="-light border-right" id="sidebar-wrapper">
          <div class="list-group list-group-flush">
            <a href="#" class="list-group-item list-group-item-action"><strong>Categories</strong></a>
            <a href="<%= new_category_url %>" class="list-group-item list-group-item-action">+ New Categories</a>
            <a href="/" class="list-group-item list-group-item-action">Priorities</a>
            <% @categories.each do |category| %>
              <a href="<%= category_path(category) %>" class="list-group-item list-group-item-action"><%= category.title %></a>
            <% end %>
          </div>
        </div>
      <% end %>

      <div class="container">
        <% if notice %>
          <div class="alert alert-success" role="alert">
            <%= notice %>
          </div>
        <% end %>

        <% if alert %>
          <div class="alert alert-danger" role="alert">
            <%= alert %>
          </div>
        <% end %>

        <%= yield %>
      </div>
    </body>
  </div>
</html>